In [40]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score

In [17]:
distances = pd.read_csv("distances_maple.csv", header=None)

In [18]:
distances

,0,1,2,3,4,5,6,7,8,9,...,502,503,504,505,506,507,508,509,510,511
0,1.376315,1.264427,0.960059,0.319121,0.769588,1.329025,0.754053,0.200818,1.282395,0.756168,...,1.151915,0.971259,0.596990,1.007380,1.122285,0.843607,0.459578,0.919924,0.950841,0.681930
1,1.371887,0.479758,0.251975,0.565764,0.627771,1.017054,0.339764,0.664346,1.314724,0.847559,...,0.349745,0.582270,0.904934,0.696448,0.517579,0.903606,0.404025,0.770833,0.760260,0.589446
2,0.596401,1.014111,1.085759,0.919860,1.304336,1.810047,1.089856,0.646040,0.515742,0.091489,...,1.025961,0.400274,0.309313,0.328228,0.661167,0.073718,0.574370,0.158120,0.202928,0.252561
3,0.786231,0.774107,0.845814,0.795902,1.120625,1.596088,0.879704,0.596871,0.721302,0.294502,...,0.777194,0.202263,0.456219,0.210203,0.445124,0.322912,0.420856,0.181014,0.185835,0.117818
4,1.404008,0.899597,0.567161,0.159131,0.509710,1.055375,0.385214,0.312949,1.321903,0.772483,...,0.771413,0.767111,0.718199,0.845328,0.836540,0.855116,0.238542,0.828508,0.842084,0.573899
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
507,1.258053,1.173282,0.911847,0.336132,0.801634,1.363593,0.735857,0.075410,1.165155,0.629951,...,1.072998,0.844044,0.484823,0.876811,1.005780,0.717968,0.353790,0.788298,0.819107,0.550854
508,2.092522,1.087685,0.605057,0.690873,0.225372,0.337118,0.433616,1.015289,2.020055,1.486023,...,0.915520,1.339881,1.445697,1.448214,1.272570,1.563162,0.938176,1.489363,1.489629,1.256769
509,0.505224,0.976121,1.120289,1.038695,1.395440,1.877565,1.160664,0.783798,0.440517,0.239305,...,1.014575,0.352257,0.455894,0.247606,0.603004,0.177894,0.676288,0.104107,0.126565,0.340702
510,0.794860,0.843742,0.871646,0.748582,1.102300,1.597387,0.877418,0.524417,0.721302,0.234701,...,0.833225,0.290633,0.372847,0.289469,0.528664,0.283762,0.381432,0.211042,0.232794,0.046313
511,0.822308,0.977628,0.941190,0.690648,1.092104,1.616260,0.900433,0.416816,0.736927,0.185633,...,0.948519,0.447230,0.230241,0.436537,0.681150,0.269272,0.363907,0.317677,0.353024,0.142549

In [6]:
train_labels = pd.read_csv("paraboloid_train_labels.csv",header=None)
train_labels

     0
0    0
1    0
2    1
3    1
4    0
..  ..
507  0
508  0
509  1
510  1
511  1

[512 rows x 1 columns]

In [7]:
test_labels = pd.read_csv("paraboloid_test_labels.csv",header=None)
test_labels

     0
0    1
1    0
2    0
3    0
4    0
..  ..
507  1
508  0
509  1
510  1
511  1

[512 rows x 1 columns]

In [51]:
distancesArr = distances.to_numpy().transpose()

In [52]:
test_labels.shape

(512, 1)

In [53]:
sorted_inds = np.argsort(distancesArr, axis=1)

In [54]:
def getpred(i):
    votes = train_labels.to_numpy()[sorted_inds[i][0:5]]
    unique_values, counts = np.unique(votes, return_counts=True)
    max_count_index = np.argmax(counts)
    most_frequent_value = unique_values[max_count_index]
    return int(most_frequent_value)

In [55]:
preds = [getpred(i) for i in range(test_labels.shape[0])]

In [56]:
accuracy_score(test_labels.to_numpy(), preds)

0.986328125

In [57]:
train_labels.to_numpy()[sorted_inds[2][0:5]]

array([[0],
       [0],
       [0],
       [0],
       [0]])

In [27]:
np.argmax(train_labels.to_numpy()[sorted_inds[0][0:5]])

np.int64(0)

In [28]:
train_labels.to_numpy()[sorted_inds[0][0:5]]

array([[1],
       [0],
       [1],
       [1],
       [0]])

In [30]:
np.unique(train_labels.to_numpy()[sorted_inds[0][0:5]], return_counts=True)

(array([0, 1]), array([2, 3]))

In [ ]:
unique_values, counts = np.unique(arr, return_counts=True)

# Find the index of the maximum count
max_count_index = np.argmax(counts)

# Get the most frequent value
most_frequent_value = unique_values[max_count_index]